name: cursor
services:
    cursor:
        build:
          context: .
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        image: cursor:latest
        ports:
          - "3000:3000"